### ISSUE TITLE
Attribute doesn't work

### ISSUE THREAD

**Issue by tsusini** [whoisandie/react-blocks#4]
Hi I have a problem , the attribute no longer works.
here is my code

```
      <Block flex layout  horizontal  alignCenter id="avatar">
```

here is the render

element.style {
  flex-grow: 1;
  flex-shrink: 1;
  flex-basis: auto;
  box-sizing: border-box;
  flex-wrap: wrap;
  display: flex;
  flex-direction: row;
  align-items: stretch;
}
it automatically wrap and align-items is stretch 
Sorry for my english can you help me please

**Comment by SamuelBolduc** [comment]
+1

**Comment by whoisandy** [comment]
@tsusini Could you elaborate more on the problem you're facing ?

**Comment by tsusini** [comment]
Yes , when I add the `alignCenter` on a `<Block>`, it doesn't work, it generates `align-center:stretch` CSS on the element and adds wrap.

**Comment by whoisandy** [comment]
@tsusini alignCenter attribute is used for vertical positioning (cross-axis). Use justifyCenter for horizontal positioning (main-axis). Also there's a slight change in 1.0.0 and 1.1.0 api, alignCenter is now just center. Check out https://github.com/whoisandie/react-blocks/blob/770426738be59df4163cb6cf42c54cb21edbdf2e/src/block.js#L31
