### ISSUE TITLE
Components inside Block do not re-render when state changes

### ISSUE THREAD

**Issue by khaledh** [whoisandie/react-blocks#5]
Given the following:

``` javascript
import React from 'react';
import Block from 'react-blocks';

class Test extends React.Component {
  constructor(props) {
    super(props);
    this.state = { message: 'hello (initial)' };
  }

  render() {
    return (
      <div>
        <a href="#" onClick={() => this.setState({ message: 'hello (modified)'})}>click me</a><br />
        state outside Block: {this.state.message}
        <Block layout horizontal>
          <Block>state inside Block: {this.state.message}</Block>
        </Block>
      </div>
    );
  }
}
```

The initial output is:

```
state outside Block: hello (initial)
state inside Block: hello (initial)
```

And after I click the "click me" link:

```
state outside Block: hello (modified)
state inside Block: hello (initial)
```

Looks like a bug. If not, then how can I force the contents of Block to re-render when state changes?

**Comment by khaledh** [comment]
I narrowed it down to the [shouldComponentUpdate()](https://github.com/whoisandie/react-blocks/blob/master/src%2Fdecorate.js#L36-L41) method in decorate.js. It looks like it's not going to re-render unless the `_media` state changes.

Not sure how to fix this, but if I force shouldComponentUpdate to always return true, then my components inside Block re-render on state change properly.

**Comment by munro** [comment]
Looks like `shouldComponentUpdate()` was added to prevent unnecessary state changes for media queries performance.  Except it breaks normal functionality, so just deleting the method fixes things.

I think a better approach would be only `setState` when the media query changes, but also the feature isn't even documented, it should be removed and put in it's own library for those who want it.

**Comment by whoisandy** [comment]
@munro Yes shouldComponentUpdate was added for perf sakes. Think componentWIllUpdate should work. Also it only sets state only when media query changes (Check out https://github.com/whoisandie/react-blocks/blob/master/src/compose.js#L168). Moreover, IMHO i think the media query part should go the the block, instead of it being another standalone library.
