### ISSUE TITLE
Compatibility with 0.14

### ISSUE THREAD

**Issue by jgoux** [whoisandie/react-blocks#7]
Hello,
I've tried the library with React v0.14, and I have these errors : 

```
Warning: Block(...): React component classes must extend React.Component
Uncaught Error: Invariant Violation: Block.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
```

Is an update planned ?

Thanks for the great lib ! :+1:

**Comment by giodamelio** [comment]
I am getting the same issue.

**Comment by whoisandy** [comment]
@jgoux @giodamelio Guys the component isn`t ported to React v0.14 yet, will be up soon. Thanks for pointing out (y)

**Comment by sinn1** [comment]
Hi whoisandie, have you got an ETA for when it will be compatible with 0.14?

**Comment by whoisandy** [comment]
@sinn1 Yep should be up this week. Also follow #8 for updates in the next version
